name: Extract changes
description: Extract changes from keep a changelog for some version
author: ultram4rine

inputs:
  changelog:
    description: Name of the changelog file
    required: true
    default: CHANGELOG.md
  version:
    description: Version for which you want to extract the changes
    required: true
  output:
    description: Name of the output file
    required: false

outputs:
  changes:
    description: Changes of the specified version

runs:
  using: node20
  main: dist/index.js

branding:
  icon: clock
  color: orange
